const Queue = require('./queue')
const queue = new Queue()
console.log(queue.isEmpty())
console.log(queue.count)
queue.enqueue('Guilherme')
queue.enqueue('Poliane')
console.log(queue.isEmpty())
console.log(queue.count)
console.log(queue.toString())
queue.enqueue('Ilza')
console.log(queue.toString())
const first = queue.dequeue()
console.log(queue.count)
console.log('primeiro da fila: ', first)
console.log(queue.toString())
console.log(queue.peek())
queue.clear()
console.log(queue.isEmpty())
console.log(queue.count)